replicaCount: 1
image:
  repository: 670115915839.dkr.ecr.eu-west-1.amazonaws.com/asp-prod-app # {"$imagepolicy": "flux-system:asp-prod-app:name"}
  pullPolicy: IfNotPresent
  tag: 2022.07.06.main-0fbf2da3-2625249776 # {"$imagepolicy": "flux-system:asp-prod-app:tag"}
container:
  env:
  - name: key
    value: something
serviceAccount:
  create: true
  name: ""
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 100Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "public"
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "false"
    alb.ingress.kubernetes.io/security-groups: "NoteJam-Alb-SG-prod"
    alb.ingress.kubernetes.io/success-codes: 200,301,302
  ingressClassName: public
  hosts:
  - ahmed-asp.pltworkshop4.com
